// 📁 File: sampleData.ts (Esteso e Ottimizzato - 20 Prodotti)
import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
    users: [
        {
            name: "Marco",
            email: "admin@example.com",
            password: "123456",
            role: "admin",
        },
        {
            name: "Luca",
            email: "user@example.com",
            password: "123456",
            role: "user",
        },
    ],
    products: [
        // --- Prodotti 1-5: Camicie ---
        {
            name: "Polo Camicia Stretch Sportiva",
            slug: "polo-sporting-stretch-shirt",
            category: "Camicie",
            description: "Questa camicia Polo Sporting combina lo stile formale con un comfort eccezionale grazie al suo innovativo tessuto stretch. Perfetta per le giornate intense in ufficio.",
            images: [ "/images/sample-products/p1-1.jpg", "/images/sample-products/p1-2.jpg" ],
            price: 59.99,
            brand: "Polo",
            rating: 4.5,
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-1.jpg",
        },
        {
            name: "Brooks Brothers Camicia Maniche Lunghe",
            slug: "brooks-brothers-long-sleeved-shirt",
            category: "Camicie",
            description: "Vivi l'eleganza classica con questa camicia a maniche lunghe di Brooks Brothers. Realizzata in cotone egiziano di alta qualità, offre traspirabilità e morbidezza ineguagliabili.",
            images: [ "/images/sample-products/p2-1.jpg", "/images/sample-products/p2-2.jpg" ],
            price: 85.9,
            brand: "Brooks Brothers",
            rating: 4.2,
            numReviews: 8,
            stock: 10,
            isFeatured: true,
            banner: "banner-2.jpg",
        },
        {
            name: "Tommy Hilfiger Camicia Classic Fit",
            slug: "tommy-hilfiger-classic-fit-dress-shirt",
            category: "Camicie",
            description: "Questa camicia Tommy Hilfiger Classic Fit unisce stile preppy americano e praticità quotidiana. Vestibilità classica, tessuto facile da stirare. Perfetta per un look curato e versatile.",
            images: [ "/images/sample-products/p3-1.jpg", "/images/sample-products/p3-2.jpg" ],
            price: 99.95,
            brand: "Tommy Hilfiger",
            rating: 4.9,
            numReviews: 3,
            stock: 1,
            isFeatured: false,
            banner: null,
        },
        {
            name: "Calvin Klein Camicia Slim Fit Stretch",
            slug: "calvin-klein-slim-fit-stretch-shirt",
            category: "Camicie",
            description: "Ideata per l'uomo dinamico, questa camicia Calvin Klein offre un taglio slim fit che esalta la silhouette. Il tessuto stretch assicura una libertà di movimento ineguagliabile e una vestibilità anti-piega.",
            images: [ "/images/sample-products/p4-1.jpg", "/images/sample-products/p4-2.jpg" ],
            price: 39.95,
            brand: "Calvin Klein",
            rating: 3.6,
            numReviews: 5,
            stock: 10,
            isFeatured: false,
            banner: null,
        },
        {
            name: "Polo Ralph Lauren Camicia Oxford",
            slug: "polo-ralph-lauren-oxford-shirt",
            category: "Camicie",
            description: "L'iconica camicia Oxford di Polo Ralph Lauren è un pilastro dello stile preppy. Realizzata con un tessuto Oxford robusto ma morbido. Ideale per un look smart-casual intramontabile.",
            images: [ "/images/sample-products/p5-1.jpg", "/images/sample-products/p5-2.jpg" ],
            price: 79.99,
            brand: "Polo",
            rating: 4.7,
            numReviews: 18,
            stock: 6,
            isFeatured: false,
            banner: null,
        },
        // --- Prodotti 6-7: Felpe ---
        {
            name: "Polo Felpa con Cappuccio Classica",
            slug: "polo-classic-pink-hoodie",
            category: "Felpe",
            description: "Questa felpa con cappuccio classica Polo è realizzata in morbido misto cotone felpato, offrendo calore e comfort superiori. Ideale per le serate fresche o per un comfort elegante e disinvolto.",
            images: [ "/images/sample-products/p6-1.jpg", "/images/sample-products/p6-2.jpg" ],
            price: 99.99,
            brand: "Polo",
            rating: 4.6,
            numReviews: 12,
            stock: 8,
            isFeatured: true,
            banner: null,
        },
        {
            name: "Adidas Originals Felpa Adicolor Girocollo",
            slug: "adidas-originals-adicolor-sweatshirt",
            category: "Felpe",
            description: "Abbraccia la nostalgia con questa felpa Adicolor. Il design girocollo classico e la spugna French Terry garantiscono una vestibilità morbida e confortevole. L'inconfondibile logo del Trifoglio ricamato aggiunge autenticità.",
            images: [ "/images/sample-products/p11-1.jpg", "/images/sample-products/p11-2.jpg" ],
            price: 65.00,
            brand: "Adidas",
            rating: 4.5,
            numReviews: 35,
            stock: 9,
            isFeatured: false,
            banner: null,
        },
        // --- Prodotti 8-9: Jeans ---
        {
            name: "Levi's 501 Jeans Original Fit",
            slug: "levis-501-original-fit-jeans",
            category: "Jeans",
            description: "Il 501 è il punto di riferimento per ogni paio di jeans. Caratterizzato dalla leggendaria vestibilità dritta, è costruito per durare. Il denim di alta qualità migliora ad ogni lavaggio.",
            images: [ "/images/sample-products/p7-1.jpg", "/images/sample-products/p7-2.jpg" ],
            price: 105.00,
            brand: "Levi's",
            rating: 4.9,
            numReviews: 95,
            stock: 18,
            isFeatured: true,
            banner: null,
        },
        {
            name: "Diesel Jeans Tapered Belther",
            slug: "diesel-jeans-tapered-belther",
            category: "Jeans",
            description: "Questi jeans Diesel Belther offrono un moderno taglio *tapered* (affusolato) con una vita regolare. La tela *dark wash* è arricchita da dettagli leggermente invecchiati per un look vissuto ma sofisticato. Ideale per un outfit serale.",
            images: [ "/images/sample-products/p13-1.jpg", "/images/sample-products/p13-2.jpg" ],
            price: 155.00,
            brand: "Diesel",
            rating: 4.3,
            numReviews: 22,
            stock: 7,
            isFeatured: false,
            banner: null,
        },
        // --- Prodotti 10-12: Capispalla ---
        {
            name: "North Face Giacca Resolve Impermeabile",
            slug: "north-face-resolve-jacket",
            category: "Capispalla",
            description: "Questa giacca (capispalla) Resolve è un capo leggero ma estremamente resistente. Dotata di tecnologia DryVent™, è totalmente impermeabile e altamente traspirante. Ideale per l'escursionismo o come protezione quotidiana.",
            images: [ "/images/sample-products/p8-1.jpg", "/images/sample-products/p8-2.jpg" ],
            price: 130.00,
            brand: "The North Face",
            rating: 4.4,
            numReviews: 40,
            stock: 15,
            isFeatured: false,
            banner: null,
        },
        {
            name: "Hugo Boss Blazer Slim Fit in Lana",
            slug: "hugo-boss-slim-fit-blazer",
            category: "Capispalla",
            description: "Questo blazer (capispalla) Hugo Boss è l'emblema della sartorialità moderna. Realizzato in pregiata miscela di lana, presenta un taglio slim fit che valorizza la figura. Perfetto per gli affari o per un evento formale.",
            images: [ "/images/sample-products/p12-1.jpg", "/images/sample-products/p12-2.jpg" ],
            price: 399.00,
            brand: "Hugo Boss",
            rating: 4.7,
            numReviews: 18,
            stock: 4,
            isFeatured: true,
            banner: null,
        },
        {
            name: "Columbia Giacca a Vento Sportiva",
            slug: "columbia-giacca-vento-sportiva",
            category: "Capispalla",
            description: "Una giacca a vento Columbia leggera e impacchettabile, perfetta per le attività all'aperto. Realizzata con tecnologia *Omni-Shade* per la protezione solare e resistenza all'acqua. Essenziale per le tue avventure estive.",
            images: [ "/images/sample-products/p14-1.jpg", "/images/sample-products/p14-2.jpg" ],
            price: 75.00,
            brand: "Columbia",
            rating: 4.1,
            numReviews: 15,
            stock: 25,
            isFeatured: false,
            banner: null,
        },
        // --- Prodotti 13-14: Abbigliamento Sportivo ---
        {
            name: "Nike Pantaloni Tech Fleece Sportswear",
            slug: "nike-sportswear-tech-fleece-pants",
            category: "Abbigliamento Sportivo",
            description: "Questi pantaloni sportivi in Tech Fleece ridefiniscono il comfort. Il tessuto innovativo è leggero, ma intrappola il calore senza ingombro. Caratterizzati da un moderno taglio affusolato.",
            images: [ "/images/sample-products/p9-1.jpg", "/images/sample-products/p9-2.jpg" ],
            price: 90.00,
            brand: "Nike",
            rating: 4.6,
            numReviews: 75,
            stock: 22,
            isFeatured: true,
            banner: null,
        },
        {
            name: "Under Armour Maglia Termica ColdGear",
            slug: "under-armour-maglia-termica-coldgear",
            category: "Abbigliamento Sportivo",
            description: "Questa maglia termica Under Armour ColdGear è il tuo alleato per gli allenamenti invernali. Mantiene il calore corporeo grazie al tessuto a doppio strato, pur restando leggera e traspirante.",
            images: [ "/images/sample-products/p15-1.jpg", "/images/sample-products/p15-2.jpg" ],
            price: 55.00,
            brand: "Under Armour",
            rating: 4.8,
            numReviews: 50,
            stock: 12,
            isFeatured: true,
            banner: null,
        },
        // --- Prodotti 15-16: T-shirt ---
        {
            name: "Zara T-shirt Basica Scollo a V",
            slug: "zara-basic-v-neck-t-shirt",
            category: "T-shirt",
            description: "Un pilastro del guardaroba. Questa T-shirt basica con scollo a V è realizzata in jersey di cotone 100% extra-morbido. Ideale come strato base o come capo casual autonomo.",
            images: [ "/images/sample-products/p10-1.jpg", "/images/sample-products/p10-2.jpg" ],
            price: 19.99,
            brand: "Zara",
            rating: 3.9,
            numReviews: 50,
            stock: 40,
            isFeatured: false,
            banner: null,
        },
        {
            name: "Guess T-shirt Logo Grafico",
            slug: "guess-t-shirt-logo-grafico",
            category: "T-shirt",
            description: "La T-shirt Guess perfetta per un look urbano. Presenta un logo grafico di grandi dimensioni sul petto. Realizzata in puro cotone, offre una vestibilità regolare e un comfort durevole.",
            images: [ "/images/sample-products/p16-1.jpg", "/images/sample-products/p16-2.jpg" ],
            price: 35.00,
            brand: "Guess",
            rating: 4.0,
            numReviews: 15,
            stock: 30,
            isFeatured: false,
            banner: null,
        },
        // --- Prodotti 17-20: Scarpe (Nuova Categoria) ---
        {
            name: "Adidas Sneakers Ultraboost 22",
            slug: "adidas-sneakers-ultraboost-22",
            category: "Scarpe",
            description: "Queste scarpe da corsa Adidas Ultraboost 22 offrono un ritorno di energia impareggiabile grazie all'intersuola Boost. Perfette per il running o per l'uso quotidiano, garantiscono ammortizzazione superiore.",
            images: [ "/images/sample-products/p17-1.jpg", "/images/sample-products/p17-2.jpg" ],
            price: 180.00,
            brand: "Adidas",
            rating: 4.8,
            numReviews: 120,
            stock: 10,
            isFeatured: true,
            banner: null,
        },
        {
            name: "Clarks Scarpe Eleganti Desert Boot",
            slug: "clarks-scarpe-eleganti-desert-boot",
            category: "Scarpe",
            description: "L'iconico Desert Boot di Clarks. Queste scarpe in pelle scamosciata offrono uno stile casual-elegante senza tempo. La suola in crepe naturale assicura comfort e durata. Perfette con jeans o chino.",
            images: [ "/images/sample-products/p18-1.jpg", "/images/sample-products/p18-2.jpg" ],
            price: 120.00,
            brand: "Clarks",
            rating: 4.5,
            numReviews: 45,
            stock: 6,
            isFeatured: false,
            banner: null,
        },
        {
            name: "Nike Scarpe da Calcio Phantom GT2",
            slug: "nike-scarpe-calcio-phantom-gt2",
            category: "Scarpe",
            description: "Queste scarpe da calcio Nike Phantom GT2 sono progettate per la precisione e il controllo di palla. Offrono un tocco eccezionale e una trazione dinamica sui campi in erba naturale.",
            images: [ "/images/sample-products/p19-1.jpg", "/images/sample-products/p19-2.jpg" ],
            price: 95.00,
            brand: "Nike",
            rating: 4.2,
            numReviews: 30,
            stock: 18,
            isFeatured: false,
            banner: null,
        },
        {
            name: "Dr. Martens Stivali 1460 Smooth",
            slug: "dr-martens-stivali-1460-smooth",
            category: "Scarpe",
            description: "Gli iconici stivali Dr. Martens 1460. Realizzati in pelle Smooth, sono resistenti e noti per il loro comfort duraturo. Un classico senza tempo, perfetto per ogni look audace.",
            images: [ "/images/sample-products/p20-1.jpg", "/images/sample-products/p20-2.jpg" ],
            price: 160.00,
            brand: "Dr. Martens",
            rating: 4.6,
            numReviews: 60,
            stock: 5,
            isFeatured: true,
            banner: null,
        },
    ],
};

export default sampleData;