import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  users: [
    {
      name: "Marco",
      email: "admin@example.com",
      password: "123456",
      role: "admin",
    },
    {
      name: "Luca",
      email: "user@example.com",
      password: "123456",
      role: "user",
    },
  ],
  products: [
    {
      name: "Polo Sporting Stretch Shirt",
      slug: "polo-sporting-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Classic Polo style with modern comfort",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 59.99,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Brooks Brothers Long Sleeved Shirt",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "Men's Dress Shirts",
      description: "Timeless style and premium comfort",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      price: 85.9,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Tommy Hilfiger Classic Fit Dress Shirt",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "Men's Dress Shirts",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 99.95,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 1, 
      isFeatured: false,
      banner: null,
    },
    {
      name: "Calvin Klein Slim Fit Stretch Shirt",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Streamlined design with flexible stretch fabric",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      price: 39.95,
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Ralph Lauren Oxford Shirt",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "Men's Dress Shirts",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 79.99,
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Classic Pink Hoodie",
      slug: "polo-classic-pink-hoodie",
      category: "Men's Sweatshirts",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 99.99,
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    // --- Nuovi Prodotti di Abbigliamento (7-12) ---
    {
      name: "Levi's 501 Original Fit Jeans",
      slug: "levis-501-original-fit-jeans",
      category: "Men's Denim",
      description: "The timeless original blue jeans. Straight fit and legendary durability.",
      images: [
        "/images/sample-products/p7-1.jpg",
        "/images/sample-products/p7-2.jpg",
      ],
      price: 105.00,
      brand: "Levi's",
      rating: 4.9,
      numReviews: 95,
      stock: 18,
      isFeatured: true,
      banner: null,
    },
    {
      name: "North Face Resolve Jacket",
      slug: "north-face-resolve-jacket",
      category: "Outerwear",
      description: "Waterproof and breathable jacket, ideal for rainy days.",
      images: [
        "/images/sample-products/p8-1.jpg",
        "/images/sample-products/p8-2.jpg",
      ],
      price: 130.00,
      brand: "The North Face",
      rating: 4.4,
      numReviews: 40,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Nike Sportswear Tech Fleece Pants",
      slug: "nike-sportswear-tech-fleece-pants",
      category: "Men's Activewear",
      description: "Lightweight and warm fleece pants with a modern tapered fit.",
      images: [
        "/images/sample-products/p9-1.jpg",
        "/images/sample-products/p9-2.jpg",
      ],
      price: 90.00,
      brand: "Nike",
      rating: 4.6,
      numReviews: 75,
      stock: 22,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Zara Basic V-Neck T-Shirt",
      slug: "zara-basic-v-neck-t-shirt",
      category: "Men's T-Shirts",
      description: "Soft cotton jersey T-shirt, perfect for layering or casual wear.",
      images: [
        "/images/sample-products/p10-1.jpg",
        "/images/sample-products/p10-2.jpg",
      ],
      price: 19.99,
      brand: "Zara",
      rating: 3.9,
      numReviews: 50,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Adidas Originals Adicolor Sweatshirt",
      slug: "adidas-originals-adicolor-sweatshirt",
      category: "Men's Sweatshirts",
      description: "Classic crewneck design with the iconic Trefoil logo.",
      images: [
        "/images/sample-products/p11-1.jpg",
        "/images/sample-products/p11-2.jpg",
      ],
      price: 65.00,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 35,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Hugo Boss Slim Fit Blazer",
      slug: "hugo-boss-slim-fit-blazer",
      category: "Men's Outerwear",
      description: "Elegant wool-blend blazer with a modern, tailored cut.",
      images: [
        "/images/sample-products/p12-1.jpg",
        "/images/sample-products/p12-2.jpg",
      ],
      price: 399.00,
      brand: "Hugo Boss",
      rating: 4.7,
      numReviews: 18,
      stock: 4,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;